### ISSUE TITLE
darwin arm64

### ISSUE THREAD

**Issue by fusionbeam** [node-3d/iohook-raub#3]
I've noticed you've added support for Macos on M chips.
Thank you for that. 
I've tested and while the dependencies are loading fine now, this package doesn't (cannot find module ./bin-darwin-arm64/iohook).
Lookin at the package install.js I see the release tag is hardcoded to 0.0.1 (const tag = '0.0.1'.
Maybe this is the reason why the binaries are not found.

Thanks again for your great work.
Rares

**Comment by raub** [comment]
yeah, that should be the case, please try https://github.com/node-3d/iohook-raub/releases/tag/0.1.1

**Comment by fusionbeam** [comment]
0.1.1 installs fine. 
thank you!
